name=ESP32 AWS MQTT Manager
version=1.0.2
author=Rohit K. Shaw
maintainer=Rohit K. Shaw
sentence=Easily connect your ESP32 to AWS IoT Core using MQTT and mutual TLS.
paragraph=A lightweight, non-blocking wrapper that abstracts away complex ESP-IDF event loops and TLS handshakes. Just pass your AWS certificates as strings and use a simple asynchronous API to publish and subscribe. Perfect for telemetry nodes and remote control projects. Requires the ESP32 core.
category=Communication
url=https://github.com/shawrhit/ESP32_AWS_MQTT_Manager
architectures=esp32
includes=mqtt_manager.h
